### ISSUE TITLE
Bug: Setting headers on a route requires the client to send matching headers.

### ISSUE THREAD

**Issue by discogestalt** [amaziahub/mimicker#10]
**Describe the bug**

When setting headers on a route, with the expectation that the response will include those headers, any requests to the route endpoint will return a 404 unless the client also includes the matching headers in the request.

**Steps/Code to reproduce bug**

```python
In [38] mock_server = mimicker(8989).routes(get("/test").headers([("test-header", "test value")]))
In [39]: resp = request("GET", "http://localhost:8989/test")

127.0.0.1 - - [11/Dec/2024 12:44:31] "GET /test HTTP/1.1" 404 -
127.0.0.1 - - [11/Dec/2024 12:44:31] Responded with 404 for GET request to /test

In [40]: resp.headers
Out[40]: {'Server': 'SimpleHTTP/0.6 Python/3.12.3', 'Date': 'Wed, 11 Dec 2024 17:44:31 GMT'}

In [41]: resp = request("GET", "http://localhost:8989/test", headers={"test-header": "test value"})

127.0.0.1 - - [11/Dec/2024 12:45:00] "GET /test HTTP/1.1" 200 -

In [42]: resp.headers
Out[42]: {'Server': 'SimpleHTTP/0.6 Python/3.12.3', 'Date': 'Wed, 11 Dec 2024 17:45:00 GMT', 'test-header': 'test value', 'Content-Type': 'application/json'}
```

**Expected behavior**

The route should match on the endpoint and return any configured headers, the client should not be required to send matching headers for a successful response.

**Comment by amaziahub** [comment]
Thank you @discogestalt, well presented issue and expected behavior this should be added and resolved in the next release

**Comment by amaziahub** [comment]
@discogestalt issue is resolved and new version released to [pypi](https://pypi.org/project/mimicker/)
